development:
  adapter: postgresql
  encoding: unicode
  database: expenseApp_development
  pool: 5
  username: expenseApp
  password: expenseApp
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: expenseApp_test
  pool: 5
  username: expenseApp
  password: expenseApp
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: expenseApp_production
  pool: 5
  username:
  password: